# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20160610_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='approx_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='genre',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
